// : Generated by xaf-index-generator :

export { default as BlockHistory } from './block.history.vue'
export { default as BlockMainForm } from './block.main-form.vue'
export { default as BlockTransferForm } from './block.transfer-form.vue'
