// : Generated by xaf-index-generator :

export { default as ContextCoin } from './context.coin.vue'
export { default as ContextDate } from './context.date.vue'
export { default as ContextTemplate } from './context.template.vue'
