// : Generated by xaf-index-generator :

export { default as AppAdaptivityFooter } from './app-adaptivity.footer.vue'
export { default as AppAdaptivityHeader } from './app-adaptivity.header.vue'
export { default as AppMenu } from './app.menu.vue'
