// : Generated by xaf-index-generator :

export { default as BlockAdaptivityHistory } from './block-adaptivity.history.vue'
export { default as BlockAdaptivityMainSection } from './block-adaptivity.main-section.vue'
