// : Generated by xaf-index-generator :

export * from './element'
export { default as TableConstruct } from './table.construct.vue'
export { default as TableTransactions } from './table.transactions.vue'
