// : Generated by xaf-index-generator :

export { default as SocialFacebook } from './social.facebook.vue'
export { default as SocialTelegram } from './social.telegram.vue'
export { default as SocialTwitter } from './social.twitter.vue'
